apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-nginx
  name: my-nginx
spec:
  template:
    spec:
      $setElementOrder/containers:
        - name: my-nginx
      containers:
        - image: nginx:1.19.6-alpine
          name: my-nginx