apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-rabbitmq
  name: my-rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-rabbitmq
  template:
    metadata:
      labels:
        app: my-rabbitmq
    spec:
      containers:
      - image: rabbitmq
        name: my-rabbitmq