apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-hello-world
  name: my-hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-hello-world
  template:
    metadata:
      labels:
        app: my-hello-world
    spec:
      containers:
      - image: hello-world
        name: my-hello-world